### ISSUE TITLE
Ignore tiny windows

### ISSUE THREAD

**Issue by sindresorhus** [karaggeorge/mac-windows#1]
I'm getting the `Bartender 3` app returned, which is only a 10px "window" (It's not actually a window in that sense).

See the logic for filtering: https://github.com/sindresorhus/active-win/blob/a31fcfce2dc1e0c0efb00361e607f7a4505a8ba6/Sources/active-win/main.swift#L18-L29

**Comment by karaggeorge** [comment]
Fixed in: https://github.com/karaggeorge/mac-windows/commit/548f319c47d81e98ab2c68ac8cea7e9b2fdd1079
